name: Sync to Azure DevOps

on:
  push:
    branches:
      - '**'  # All branches

jobs:
  push-to-azure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v3

    - name: Setup Git config
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Push to Azure DevOps
      env:
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
      run: |
        # Add Azure DevOps repo as remote with PAT authentication
        git remote add azure "https://${{ env.AZURE_DEVOPS_PAT }}@dev.azure.com/thekaranjitdevopslab/CloudResumeChallange/_git/CloudResumeChallange"
        # Push all branches and tags forcefully
        git push azure --all --force
        git push azure --tags --force
